name: Run tests

on:
  push:

jobs:

  clojure:

    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare java
        uses: actions/setup-java@v2.1.0
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@3.5
        with:
          # Install just one or all simultaneously
          cli: 1.10.3.855 # Clojure CLI based on tools.deps

      - name: Execute tests
        run: clojure -Mdev:test
        shell: bash